import { Language, Theme } from '../types';

export type TranslationKey = 
  | 'heroTitle' 
  | 'heroSubtitle' 
  | 'cta_primary' 
  | 'cta_secondary' 
  | 'missing_middle' 
  | 'demo_status'
  | 'nav_docs'
  | 'nav_signin'
  | 'theme_ranch'
  | 'theme_edge'
  | 'theme_legal'
  | 'theme_corporate'
  | 'stat_events'
  | 'stat_sources'
  | 'stat_pending'
  | 'stat_sync'
  | 'col_time'
  | 'col_source'
  | 'col_category'
  | 'col_type'
  | 'col_detail'
  | 'settings_title'
  | 'docs_flashcards_title'
  | 'card_q1' | 'card_a1'
  | 'card_q2' | 'card_a2'
  | 'card_q3' | 'card_a3'
  | 'card_q4' | 'card_a4'
  | 'card_q5' | 'card_a5'
  | 'card_q6' | 'card_a6'
  | 'card_q7' | 'card_a7'
  | 'card_q8' | 'card_a8'
  | 'sidebar_getting_started'
  | 'sidebar_integration'
  | 'sec_overview'
  | 'sec_media'
  | 'sec_simulation'
  | 'sec_themes'
  | 'sec_backend'
  | 'sec_api'
  | 'sec_wiring'
  | 'doc_knowledge_center'
  | 'doc_knowledge_desc'
  | 'doc_reports_title'
  | 'doc_video_title'
  | 'doc_infographic_title'
  | 'landing_why_title'
  | 'landing_why_desc'
  | 'landing_arch_title'
  | 'landing_arch_desc'
  | 'landing_own_title'
  | 'landing_own_desc'
  | 'landing_get_access'
  | 'landing_self_host'
  | 'landing_view_demo'
  | 'footer_privacy'
  | 'footer_status'
  | 'hero_tagline'
  | 'promo_audio_title'
  | 'promo_audio_desc'
  | 'promo_audio_btn'
  | 'usecase_ranch_desc'
  | 'usecase_edge_desc'
  | 'usecase_legal_desc'
  | 'usecase_corporate_desc'
  | 'arch_1_title' | 'arch_1_desc' | 'arch_1_highlight'
  | 'arch_2_title' | 'arch_2_desc'
  | 'arch_3_title' | 'arch_3_desc' | 'arch_3_highlight'
  // Dynamic Theme Keys
  | 'sidebar_label_edge' | 'sidebar_label_ranch' | 'sidebar_label_legal' | 'sidebar_label_corporate'
  | 'all_sources_edge' | 'all_sources_ranch' | 'all_sources_legal' | 'all_sources_corporate'
  | 'stat_active_edge' | 'stat_active_ranch' | 'stat_active_legal' | 'stat_active_corporate';

export const DICTIONARY: Record<Language, Record<TranslationKey, string>> = {
  en: {
    heroTitle: "Analytics for the Air-Gapped World",
    heroSubtitle: "The visibility of a modern dashboard with the resilience of an industrial logger. Run offline. Sync when the satellite links up.",
    cta_primary: "Enter Mission Control",
    cta_secondary: "Open Source (MIT)",
    missing_middle: "Enterprise IoT stacks are too heavy. Basic log files are too simple.",
    demo_status: "Simulating context",
    nav_docs: "Docs",
    nav_signin: "Sign In",
    theme_ranch: "Agritech & Field",
    theme_edge: "Maritime & Logistics",
    theme_legal: "Secure Facilities",
    theme_corporate: "Fun-EE (Legacy Ops)",
    stat_events: "Events Today",
    stat_sources: "Active Sources",
    stat_pending: "Pending Sync",
    stat_sync: "Last Sync",
    col_time: "Time",
    col_source: "Source",
    col_category: "Category",
    col_type: "Type",
    col_detail: "Detail",
    settings_title: "Node Configuration",
    docs_flashcards_title: "Concept Flashcards",
    card_q1: "What is the primary function of EdgeKite?",
    card_a1: "It is a unified, lightweight, offline-first event collection platform for resource-constrained edge devices.",
    card_q2: "What is the 'Gateway' Strategy?",
    card_a2: "Providing industry-specific user interfaces (lingo, icons, metrics) on top of a universal technical core.",
    card_q3: "What is the 'Missing Middle'?",
    card_a3: "The gap between heavy enterprise IoT stacks (AWS Greengrass) and simple raw log files.",
    card_q4: "What is the target RAM footprint?",
    card_a4: "Less than 100MB, suitable for Raspberry Pi 4/5 or small VPS instances.",
    card_q5: "Operational vs Analytical Truth?",
    card_a5: "Edge = Raw, fast (Operational). Hub = Corrected, enriched (Analytical).",
    card_q6: "How is sync handled?",
    card_a6: "Using the 'Outbox Pattern'. Events are stored locally first (synced=0), then batched to the hub.",
    card_q7: "Why use separate timestamps?",
    card_a7: "We store 'observed_at' (occurrence) and 'received_at' (ingest) to handle clock drift.",
    card_q8: "Why Rust + SQLite?",
    card_a8: "High performance, memory safety, and single-binary simplicity perfect for edge deployments.",
    
    // Docs & Nav
    sidebar_getting_started: "Getting Started",
    sidebar_integration: "Integration",
    sec_overview: "Project Status",
    sec_media: "Media & Resources",
    sec_simulation: "Simulation vs Real",
    sec_themes: "Theme System",
    sec_backend: "Backend Guide",
    sec_api: "API Endpoints",
    sec_wiring: "Wiring Guide",
    doc_knowledge_center: "Knowledge Center",
    doc_knowledge_desc: "Deep dives, audio briefings, and study materials generated by Google NotebookLM.",
    doc_reports_title: "Briefings & Reports",
    doc_video_title: "Video Briefing",
    doc_infographic_title: "System Architecture Infographic",
    
    // Landing Sections
    landing_why_title: "Why EdgeKite?",
    landing_why_desc: "EdgeKite fits the \"Missing Middle\"—providing a unified dashboard for field operations.",
    landing_arch_title: "The \"Kite\" Architecture",
    landing_arch_desc: "A kite flies independently on the wind (Edge), but is tethered to the ground (Hub). If the string breaks, the kite keeps flying.",
    landing_own_title: "Own your telemetry.",
    landing_own_desc: "Whether you are monitoring a single server or a fleet of 500 remote sensors, EdgeKite gives you the data you need without the bloat.",
    landing_get_access: "Get Early Access",
    landing_self_host: "Self-host now",
    landing_view_demo: "View Demo Dashboard",
    footer_privacy: "Privacy",
    footer_status: "Status",

    // New Cleanups
    hero_tagline: "The \"Missing Middle\" of Observability",
    promo_audio_title: "Audio Deep Dive",
    promo_audio_desc: "Listen to the 14-minute Audio Deep Dive generated by Google NotebookLM. It breaks down the architecture and trade-offs while you work.",
    promo_audio_btn: "Listen Now in Docs",
    usecase_ranch_desc: "Farmers need to view NVR detections and sensor data on their phone via local WiFi, even when the uplink is down. Sync to the farmhouse server at night.",
    usecase_edge_desc: "Container ships operate \"air-gapped\" for weeks. Collect telemetry locally on the bridge, then burst-sync to HQ when satellite connectivity is affordable.",
    usecase_legal_desc: "Legal review rooms and secure SCIFs must remain air-gapped. Track document access locally, aggregating to a central compliance dashboard only via secure diode.",
    usecase_corporate_desc: "Fun-EE: The 'Boring App' Monitor. Drop a script into your legacy Intranet, HR Portal, or CRM. See why 'it feels slow' without buying an Enterprise License.",
    
    arch_1_title: "The Kite (Edge Node)",
    arch_1_desc: "Lightweight binary running on your hardware. Collects events, stores them in SQLite, and serves the local dashboard.",
    arch_1_highlight: "Operational Truth.",
    
    arch_2_title: "The String (Sync)",
    arch_2_desc: "An efficient \"Outbox Pattern\" syncs batches of events only when connectivity is available. Resilient to power loss and bad networks.",
    
    arch_3_title: "The Ground (Central Hub)",
    arch_3_desc: "Your aggregation server. Could be a cloud instance, or a Mac Mini in the barn office. Aggregates data from all your Kites.",
    arch_3_highlight: "Analytical Truth.",

    // Dynamic Theme Vocabulary
    sidebar_label_edge: "Sources",
    sidebar_label_ranch: "Field Assets",
    sidebar_label_legal: "Custodians",
    sidebar_label_corporate: "Cost Centers",

    all_sources_edge: "All Sources",
    all_sources_ranch: "All Assets",
    all_sources_legal: "All Nodes",
    all_sources_corporate: "All Legacy Apps",

    stat_active_edge: "Active Sources",
    stat_active_ranch: "Active Assets",
    stat_active_legal: "Active Nodes",
    stat_active_corporate: "Active Apps"
  },
  es: {
    heroTitle: "Analítica para el Mundo Desconectado",
    heroSubtitle: "La visibilidad de un dashboard moderno con la resistencia de un registrador industrial. Ejecute offline. Sincronice cuando haya satélite.",
    cta_primary: "Entrar al Control",
    cta_secondary: "Código Abierto (MIT)",
    missing_middle: "Las soluciones IoT empresariales son muy pesadas. Los logs básicos son muy simples.",
    demo_status: "Simulando contexto",
    nav_docs: "Documentación",
    nav_signin: "Entrar",
    theme_ranch: "Agrotech y Campo",
    theme_edge: "Marítimo y Logística",
    theme_legal: "Instalaciones Seguras",
    theme_corporate: "Fun-EE (Legacy Ops)",
    stat_events: "Eventos Hoy",
    stat_sources: "Fuentes Activas",
    stat_pending: "Pendiente Sync",
    stat_sync: "Último Sync",
    col_time: "Hora",
    col_source: "Fuente",
    col_category: "Categoría",
    col_type: "Tipo",
    col_detail: "Detalle",
    settings_title: "Configuración del Nodo",
    docs_flashcards_title: "Tarjetas de Conceptos",
    card_q1: "¿Cuál es la función principal de EdgeKite?",
    card_a1: "Es una plataforma unificada, ligera y offline-first de recolección de eventos para dispositivos limitados.",
    card_q2: "¿Qué es la Estrategia 'Gateway'?",
    card_a2: "Proporcionar interfaces específicas para la industria (jerga, iconos) sobre un núcleo técnico universal.",
    card_q3: "¿Qué es el 'Missing Middle'?",
    card_a3: "La brecha entre pilas IoT empresariales pesadas (AWS Greengrass) y archivos de registro simples.",
    card_q4: "¿Cuál es el objetivo de RAM?",
    card_a4: "Menos de 100MB, adecuado para Raspberry Pi 4/5 o pequeñas instancias VPS.",
    card_q5: "¿Verdad Operativa vs Analítica?",
    card_a5: "Edge = Datos crudos (Operativa). Hub = Datos enriquecidos (Analítica).",
    card_q6: "¿Cómo se maneja la sincronización?",
    card_a6: "Usando el patrón 'Outbox'. Se guarda localmente primero, luego se envía por lotes.",
    card_q7: "¿Por qué timestamps separados?",
    card_a7: "Guardamos 'observed_at' (ocurrencia) y 'received_at' (ingesta) para manejar la deriva del reloj.",
    card_q8: "¿Por qué Rust + SQLite?",
    card_a8: "Alto rendimiento, seguridad de memoria y simplicidad de un solo binario.",

    sidebar_getting_started: "Primeros Pasos",
    sidebar_integration: "Integración",
    sec_overview: "Estado del Proyecto",
    sec_media: "Media y Recursos",
    sec_simulation: "Simulación vs Real",
    sec_themes: "Sistema de Temas",
    sec_backend: "Guía Backend",
    sec_api: "Endpoints API",
    sec_wiring: "Guía de Cableado",
    doc_knowledge_center: "Centro de Conocimiento",
    doc_knowledge_desc: "Análisis profundos, resúmenes de audio y materiales generados por Google NotebookLM.",
    doc_reports_title: "Informes y Reportes",
    doc_video_title: "Video Resumen",
    doc_infographic_title: "Infografía de Arquitectura",

    landing_why_title: "¿Por qué EdgeKite?",
    landing_why_desc: "EdgeKite encaja en el \"Missing Middle\"—proveyendo un dashboard unificado para operaciones de campo.",
    landing_arch_title: "La Arquitectura \"Kite\" (Cometa)",
    landing_arch_desc: "EdgeKite ('Cometa del Borde') vuela independiente en el viento, pero atada al suelo (Hub). Si la cuerda se rompe, sigue volando.",
    landing_own_title: "Dueño de su telemetría.",
    landing_own_desc: "Ya sea que monitoree un servidor o una flota de 500 sensores remotos, EdgeKite le da los datos que necesita sin el peso extra.",
    landing_get_access: "Acceso Anticipado",
    landing_self_host: "Auto-hospedar ahora",
    landing_view_demo: "Ver Demo",
    footer_privacy: "Privacidad",
    footer_status: "Estado",

    hero_tagline: "El \"Missing Middle\" de la Observabilidad",
    promo_audio_title: "Análisis de Audio Profundo",
    promo_audio_desc: "Escuche el análisis de 14 minutos generado por Google NotebookLM. Desglosa la arquitectura y las ventajas mientras trabaja.",
    promo_audio_btn: "Escuchar en Docs",
    usecase_ranch_desc: "Los agricultores necesitan ver detecciones NVR y datos de sensores en su teléfono vía WiFi local, incluso sin conexión. Sincronice por la noche.",
    usecase_edge_desc: "Los portacontenedores operan desconectados por semanas. Recopile telemetria localmente en el puente, luego sincronice cuando sea asequible.",
    usecase_legal_desc: "Las salas de revisión legal y SCIFs deben permanecer aislados. Rastree el acceso a documentos localmente y agregue al panel central.",
    usecase_corporate_desc: "Fun-EE: El monitor de 'Apps Aburridas'. Ponga un script en su Intranet legacy y vea por qué es lento sin pagar licencias Enterprise.",

    arch_1_title: "La Cometa (Nodo Edge)",
    arch_1_desc: "Binario ligero en su hardware. Recopila eventos, los guarda en SQLite y sirve el panel local.",
    arch_1_highlight: "Verdad Operativa.",
    
    arch_2_title: "La Cuerda (Sync)",
    arch_2_desc: "Un patrón \"Outbox\" eficiente sincroniza lotes de eventos solo cuando hay conectividad. Resistente a cortes de energía.",
    
    arch_3_title: "El Suelo (Hub Central)",
    arch_3_desc: "Su servidor de agregación. Puede ser una instancia en la nube o un Mac Mini en la oficina. Agrega datos de todas sus Cometas.",
    arch_3_highlight: "Verdad Analítica.",

    // Dynamic Theme Vocabulary (ES)
    sidebar_label_edge: "Fuentes",
    sidebar_label_ranch: "Activos de Campo",
    sidebar_label_legal: "Custodios",
    sidebar_label_corporate: "Centros de Costo",

    all_sources_edge: "Todas las Fuentes",
    all_sources_ranch: "Todos los Activos",
    all_sources_legal: "Todos los Nodos",
    all_sources_corporate: "Todas las Apps",

    stat_active_edge: "Fuentes Activas",
    stat_active_ranch: "Activos Activos",
    stat_active_legal: "Nodos Activos",
    stat_active_corporate: "Apps Activas"
  },
  pt: {
    heroTitle: "Analytics para o Mundo Offline",
    heroSubtitle: "A visibilidade de um dashboard moderno com a resiliência industrial. Rode offline. Sincronize quando o satélite conectar.",
    cta_primary: "Acessar Painel",
    cta_secondary: "Código Aberto (MIT)",
    missing_middle: "Pilhas de IoT corporativas são pesadas demais. Logs básicos são simples demais.",
    demo_status: "Simulando contexto",
    nav_docs: "Docs",
    nav_signin: "Entrar",
    theme_ranch: "Agritech e Campo",
    theme_edge: "Marítimo e Logística",
    theme_legal: "Áreas Seguras",
    theme_corporate: "Fun-EE (Legacy Ops)",
    stat_events: "Eventos Hoje",
    stat_sources: "Fontes Ativas",
    stat_pending: "Pendente Sync",
    stat_sync: "Último Sync",
    col_time: "Hora",
    col_source: "Origem",
    col_category: "Categoria",
    col_type: "Tipo",
    col_detail: "Detalhe",
    settings_title: "Configuração do Nó",
    docs_flashcards_title: "Flashcards de Conceito",
    card_q1: "Qual é a função principal do EdgeKite?",
    card_a1: "Plataforma unificada, leve e offline-first para coleta de eventos em dispositivos limitados.",
    card_q2: "O que é a Estratégia 'Gateway'?",
    card_a2: "Fornecer interfaces específicas da indústria (jargão, ícones) sobre um núcleo técnico universal.",
    card_q3: "O que é o 'Missing Middle'?",
    card_a3: "A lacuna entre pilhas pesadas de IoT corporativo e arquivos de log simples.",
    card_q4: "Qual é a meta de RAM?",
    card_a4: "Menos de 100MB, adequado para Raspberry Pi 4/5 ou VPS pequeno.",
    card_q5: "Verdade Operacional vs Analítica?",
    card_a5: "Edge = Dados brutos (Operacional). Hub = Dados enriquecidos (Analítica).",
    card_q6: "Como a sincronização funciona?",
    card_a6: "Usando o padrão 'Outbox'. Salva localmente primeiro, depois envia em lote.",
    card_q7: "Por que timestamps separados?",
    card_a7: "Armazenamos 'observed_at' (ocorrência) e 'received_at' (ingestão) para desvios de relógio.",
    card_q8: "Por que Rust + SQLite?",
    card_a8: "Alto desempenho, segurança de memória e binário único perfeito para edge.",

    sidebar_getting_started: "Primeiros Passos",
    sidebar_integration: "Integração",
    sec_overview: "Status do Projeto",
    sec_media: "Mídia e Recursos",
    sec_simulation: "Simulação vs Real",
    sec_themes: "Sistema de Temas",
    sec_backend: "Guia Backend",
    sec_api: "Endpoints API",
    sec_wiring: "Guia de Conexão",
    doc_knowledge_center: "Centro de Conhecimento",
    doc_knowledge_desc: "Mergulhos profundos, áudios e materiais de estudo gerados pelo Google NotebookLM.",
    doc_reports_title: "Relatórios e Briefings",
    doc_video_title: "Resumo em Vídeo",
    doc_infographic_title: "Infográfico da Arquitetura",

    landing_why_title: "Por que EdgeKite?",
    landing_why_desc: "EdgeKite preenche o \"Missing Middle\"—fornecendo um painel unificado para operações de campo.",
    landing_arch_title: "A Arquitetura \"Kite\" (Pipa)",
    landing_arch_desc: "EdgeKite ('Pipa da Borda') voa independente ao vento, mas presa ao chão (Hub). Se a linha quebra, ela continua voando.",
    landing_own_title: "Sua telemetria.",
    landing_own_desc: "Seja monitorando um servidor ou uma frota de 500 sensores remotos, EdgeKite oferece os dados sem o peso extra.",
    landing_get_access: "Acesso Antecipado",
    landing_self_host: "Auto-hospedar agora",
    landing_view_demo: "Ver Demo",
    footer_privacy: "Privacidade",
    footer_status: "Status",

    hero_tagline: "O \"Missing Middle\" da Observabilidade",
    promo_audio_title: "Mergulho Profundo em Áudio",
    promo_audio_desc: "Ouça a análise de 14 minutos gerada pelo Google NotebookLM. Detalha a arquitetura e os trade-offs enquanto você trabalha.",
    promo_audio_btn: "Ouvir no Docs",
    usecase_ranch_desc: "Fazendeiros precisam ver detecções de NVR e sensores no celular via WiFi local, mesmo sem internet. Sincronize à noite.",
    usecase_edge_desc: "Navios operam desconectados por semanas. Colete telemetria localmente na ponte, depois sincronize com a sede quando viável.",
    usecase_legal_desc: "Salas jurídicas e SCIFs devem permanecer isolados. Rastreie acesso a documentos localmente, agregando ao painel central via diodo seguro.",
    usecase_corporate_desc: "Fun-EE: O monitor de 'Apps Chatas'. Coloque um script na sua Intranet ou CRM legado. Veja por que está lento sem pagar licenças caras.",

    arch_1_title: "A Pipa (Nó Edge)",
    arch_1_desc: "Binário leve no seu hardware. Coleta eventos, armazena no SQLite e serve o painel local.",
    arch_1_highlight: "Verdade Operacional.",
    
    arch_2_title: "A Linha (Sync)",
    arch_2_desc: "Um padrão \"Outbox\" eficiente sincroniza lotes de eventos apenas quando há conectividad. Resiliente a quedas de energia.",
    
    arch_3_title: "O Solo (Hub Central)",
    arch_3_desc: "Seu servidor de agregação. Pode ser na nuvem ou um servidor no escritório. Agrega dados de todas as suas Pipas.",
    arch_3_highlight: "Verdade Analítica.",

    // Dynamic Theme Vocabulary (PT)
    sidebar_label_edge: "Fontes",
    sidebar_label_ranch: "Ativos de Campo",
    sidebar_label_legal: "Custodiantes",
    sidebar_label_corporate: "Centros de Custo",

    all_sources_edge: "Todas as Fontes",
    all_sources_ranch: "Todos os Ativos",
    all_sources_legal: "Todos os Nós",
    all_sources_corporate: "Todas as Apps",

    stat_active_edge: "Fontes Ativas",
    stat_active_ranch: "Ativos Ativos",
    stat_active_legal: "Nós Ativos",
    stat_active_corporate: "Apps Ativos"
  },
  de: {
    heroTitle: "Analytik für die Offline-Welt",
    heroSubtitle: "Die Sichtbarkeit eines modernen Dashboards mit der Resilienz eines Industrie-Loggers. Offline ausführen. Synchronisieren bei Verbindung.",
    cta_primary: "Kontrollzentrum",
    cta_secondary: "Open Source (MIT)",
    missing_middle: "Enterprise IoT ist zu schwerfällig. Einfache Logdateien sind zu simpel.",
    demo_status: "Simuliere Kontext",
    nav_docs: "Doku",
    nav_signin: "Anmelden",
    theme_ranch: "Agrartechnologie",
    theme_edge: "Schifffahrt & Logistik",
    theme_legal: "Sicherheitsbereiche",
    theme_corporate: "Fun-EE (Legacy Ops)",
    stat_events: "Ereignisse Heute",
    stat_sources: "Aktive Quellen",
    stat_pending: "Warteschlange",
    stat_sync: "Letzter Sync",
    col_time: "Zeit",
    col_source: "Quelle",
    col_category: "Kategorie",
    col_type: "Typ",
    col_detail: "Detail",
    settings_title: "Knotenkonfiguration",
    docs_flashcards_title: "Konzept-Lernkarten",
    card_q1: "Was ist die Hauptfunktion von EdgeKite?",
    card_a1: "Eine leichte Offline-First-Plattform zur Ereignissammlung für beschränkte Edge-Geräte.",
    card_q2: "Was ist die 'Gateway'-Strategie?",
    card_a2: "Branchenspezifische UIs (Jargon, Icons) auf einem universellen technischen Kern.",
    card_q3: "Was ist die 'Missing Middle'?",
    card_a3: "Die Lücke zwischen schweren Enterprise-IoT-Stacks und einfachen Logdateien.",
    card_q4: "Was ist der Ziel-RAM?",
    card_a4: "Weniger als 100 MB, geeignet für Raspberry Pi 4/5 oder kleine VPS.",
    card_q5: "Operative vs. Analytische Wahrheit?",
    card_a5: "Edge = Rohdaten (Operativ). Hub = Angereicherte Daten (Analytisch).",
    card_q6: "Wie funktioniert der Sync?",
    card_a6: "Mit dem 'Outbox-Muster'. Erst lokal speichern, dann stapelweise senden.",
    card_q7: "Warum separate Zeitstempel?",
    card_a7: "Wir speichern 'observed_at' und 'received_at', um Uhrendrift zu behandeln.",
    card_q8: "Warum Rust + SQLite?",
    card_a8: "Hohe Leistung, Speichersicherheit und Einzel-Binary, perfekt für Edge.",

    sidebar_getting_started: "Erste Schritte",
    sidebar_integration: "Integration",
    sec_overview: "Projektstatus",
    sec_media: "Medien & Ressourcen",
    sec_simulation: "Simulation vs. Real",
    sec_themes: "Designsystem",
    sec_backend: "Backend-Guide",
    sec_api: "API-Endpunkte",
    sec_wiring: "Verkabelung",
    doc_knowledge_center: "Wissenszentrum",
    doc_knowledge_desc: "Deep Dives, Audio-Briefings und Lernmaterialien generiert von Google NotebookLM.",
    doc_reports_title: "Berichte & Briefings",
    doc_video_title: "Video-Zusammenfassung",
    doc_infographic_title: "Systemarchitektur-Infografik",

    landing_why_title: "Warum EdgeKite?",
    landing_why_desc: "EdgeKite füllt die \"Missing Middle\" – und bietet ein einheitliches Dashboard für den Feldeinsatz.",
    landing_arch_title: "Die \"Kite\" (Drachen) Architektur",
    landing_arch_desc: "EdgeKite ('Rand-Drachen') fliegt unabhängig im Wind, ist aber am Boden verankert (Hub). Reißt die Schnur, fliegt er weiter.",
    landing_own_title: "Ihre Telemetrie.",
    landing_own_desc: "Ob ein Server oder 500 Sensoren: EdgeKite liefert die Daten ohne Ballast.",
    landing_get_access: "Vorabzugang",
    landing_self_host: "Selbst hosten",
    landing_view_demo: "Demo ansehen",
    footer_privacy: "Datenschutz",
    footer_status: "Status",

    hero_tagline: "Die \"Missing Middle\" der Observability",
    promo_audio_title: "Audio-Deep-Dive",
    promo_audio_desc: "Hören Sie die 14-minütige Analyse von Google NotebookLM. Erläutert Architektur und Kompromisse während der Arbeit.",
    promo_audio_btn: "Jetzt in Docs hören",
    usecase_ranch_desc: "Landwirte müssen Sensordaten lokal via WLAN sehen, auch ohne Uplink. Synchronisation mit dem Hof-Server bei Nacht.",
    usecase_edge_desc: "Containerschiffe sind wochenlang offline. Telemetrie lokal auf der Brücke sammeln, dann synchronisieren, wenn Satellit verfügbar ist.",
    usecase_legal_desc: "Rechtsabteilungen und Sicherheitsräume müssen isoliert bleiben. Dokumentenzugriffe lokal verfolgen, nur sicher aggregieren.",
    usecase_corporate_desc: "Fun-EE: Der Monitor für 'Langweilige Apps'. Skript ins Legacy-Intranet werfen und sehen, warum es langsam ist, ohne teure Lizenzen.",
    
    arch_1_title: "Der Drachen (Edge Node)",
    arch_1_desc: "Leichte Binary auf Ihrer Hardware. Sammelt Events, speichert in SQLite und liefert das lokale Dashboard.",
    arch_1_highlight: "Operative Wahrheit.",
    
    arch_2_title: "Die Schnur (Sync)",
    arch_2_desc: "Ein effizientes \"Outbox-Muster\" synchronisiert Batches nur bei Verbindung. Resilient gegen Stromausfälle.",
    
    arch_3_title: "Der Boden (Zentraler Hub)",
    arch_3_desc: "Ihr Aggregationsserver. Cloud-Instanz oder Mac Mini im Büro. Aggregiert Daten aller Drachen.",
    arch_3_highlight: "Analytische Wahrheit.",

    // Dynamic Theme Vocabulary (DE)
    sidebar_label_edge: "Quellen",
    sidebar_label_ranch: "Feldanlagen",
    sidebar_label_legal: "Verwahrer",
    sidebar_label_corporate: "Kostenstellen",

    all_sources_edge: "Alle Quellen",
    all_sources_ranch: "Alle Anlagen",
    all_sources_legal: "Alle Knoten",
    all_sources_corporate: "Alle Apps",

    stat_active_edge: "Aktive Quellen",
    stat_active_ranch: "Aktive Anlagen",
    stat_active_legal: "Aktive Knoten",
    stat_active_corporate: "Aktive Apps"
  }
};

export const getTranslation = (lang: Language, key: TranslationKey): string => {
  const dict = DICTIONARY[lang] || DICTIONARY['en'];
  return dict[key] || DICTIONARY['en'][key] || key;
};